import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainNav } from '@/components/MainNav'
import { TenantProvider } from '@/contexts/TenantContext'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout 是 Next.js 应用的根布局组件
// 它包装了应用中的所有页面
// 用于定义共享的UI元素，比如导航栏、页脚等
// 也用于设置全局样式和字体
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TenantProvider>
          <MainNav />
          <main className="pt-14">
            {children}
          </main>
        </TenantProvider>
      </body>
    </html>
  );
}
